# Generated by Django 5.1.3 on 2024-12-04 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_brand_order_total_product_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 0, 57, 53, 720588)),
        ),
    ]
