# Generated by Django 5.1.2 on 2024-12-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Nhà đất', 'Nhà đất'), ('Chung cư', 'Chung cư')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='LandHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_sqm', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floors', models.CharField(blank=True, max_length=50, null=True)),
                ('total_floor_area', models.CharField(blank=True, max_length=50, null=True)),
                ('land_area', models.CharField(blank=True, max_length=50, null=True)),
                ('frontage', models.CharField(blank=True, max_length=100, null=True)),
                ('frontage_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('road_width', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_to_main_road', models.CharField(blank=True, max_length=100, null=True)),
                ('real_estate_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_sqm', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bedrooms', models.CharField(blank=True, max_length=50, null=True)),
                ('usable_area', models.CharField(blank=True, max_length=50, null=True)),
                ('balcony_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=50, null=True)),
                ('location_in_building', models.CharField(blank=True, max_length=50, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=50, null=True)),
                ('view', models.CharField(blank=True, max_length=100, null=True)),
                ('floor_range', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('furniture_status', models.CharField(blank=True, max_length=50, null=True)),
                ('furniture_included', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_area', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('real_estate_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
