# Generated by Django 5.1.2 on 2024-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_type_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='ecommerce/pimage'),
        ),
        migrations.AlterField(
            model_name='landhouse',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='ecommerce/pimage'),
        ),
    ]
